### ISSUE TITLE
Individual viral gene output?

### ISSUE THREAD

**Issue by KevinMaroney** [yyoshiaki/VIRTUS2#27]
Hello, I promise this is the last question. With your help and changing some of the "list" things in VIRTUS_wrapper.py, I was able to get individual summary and coverage files for every sample of mine. However, they are pretty much all infected with the HPV type that causes the cancer (which is expected and helps me trust its validity - one set is recurrent and the other non-recurrent). 

Is there an implementation for determining relative coverage of individual viral genes as you have under the main Github? Thank you.

P.S. I was also intrigued by your claim that this could be used for scRNA-seq data. From what I understand you would treat the GEX files of 10X as individual fastas to align to complete genomes then focus analysis on the most "interesting" virus which is present in sample using normal cellranger workflow by tacking on that viral reference before cellranger count or cellranger multi yes?

**Comment by yyoshiaki** [comment]
Regarding the quantification of individual viral gene quantification, actually VIRTUS1 included the pipeline, but I removed it in VIRTUS2. VIRTUS2 is re-designed to screen rather than look at a single virus with the newly introduced viral gene coverage filter.
You can try VIRTUS1 to quantify viral genes. 

> you would treat the GEX files of 10X as individual fastas to align to complete genomes then focus analysis on the most "interesting" virus which is present in sample using normal cellranger workflow by tacking on that viral reference before cellranger count or cellranger multi yes?

Yes. Because Cellranger discards multi-mapped reads, if the viral genome is so compact that multiple genes are overlapped, other tools such as alevin may be more suitable for the quantification.
