### ISSUE TITLE
Adding STAR options for run

### ISSUE THREAD

**Issue by cd-scientist** [yyoshiaki/VIRTUS2#8]
I am having an issue where the percentage of unmapped reads after STAR alignment is very high (~97%) due mainly to being too short. I would like to be able to add the STAR option of outFilterScoreMinOverLread and outFilterMatchNminOverLread. Where in the pathway should I add these options?

**Comment by yyoshiaki** [comment]
What is the read length? I think, for example, SE50 is no problem to map at least.
Shorter leads should be problematic for mapping to not only humans but also viruses because viruses are easily mismapped though we are making full effort to prevent mismapping.

Another possibility here is that you used not human RNAseq data. 

Of course, you can add several options to STAR steps by modifying the tool cwl files https://github.com/yyoshiaki/VIRTUS2/tree/master/tool/star .
